; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "DNA Pen"
#define MyAppVersion "1.1"
#define MyAppPublisher "Gupta Lab"
#define MyAppURL "http://www.guptalab.org/dnapen"
#define MyAppExeName "DNA Pen.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{18818274-8943-47A7-98EC-87FFC081CCEA}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={#MyAppName}
DefaultGroupName={#MyAppName}
LicenseFile=C:\Users\shikhar\Desktop\DNAPen_160514\docs\License.txt
OutputDir=C:\Users\shikhar\Desktop\DNAPen_160514
OutputBaseFilename=setup
SetupIconFile=C:\Users\shikhar\Desktop\DNAPen_160514\logo.ico
Compression=lzma
SolidCompression=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Users\shikhar\Desktop\DNAPen_160514\DNA Pen.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\shikhar\Desktop\DNAPen_160514\configFile"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\shikhar\Desktop\DNAPen_160514\filename.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\shikhar\Desktop\DNAPen_160514\final.csv"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\shikhar\Desktop\DNAPen_160514\inputfile.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\shikhar\Desktop\DNAPen_160514\logo.ico"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\shikhar\Desktop\DNAPen_160514\rsec.png"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\shikhar\Desktop\DNAPen_160514\sample456.png"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\shikhar\Desktop\DNAPen_160514\docs\*"; DestDir: "{app}\docs"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\Users\shikhar\Desktop\DNAPen_160514\images\*"; DestDir: "{app}\images"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"
Name: "{commondesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

